### ISSUE TITLE
Вывести ступенчатый график из 10-ти точек

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-chart#1]
Без прореживания, в отдельном бранче feature/ten_points

**Comment by LeKaitoW** [comment]
Для построения ступенчатого графика можно обойтись без `plot.setRenderer`, используя `ChartFactory.createXYStepChart`.
Но если использовать `renderer`, который строит не ступенчатый график, то и на выходе будет не ступенчатый, т.е. он "переопределяет" `ChartFactory.createXYStepChart`.

**Comment by aurusov** [comment]
Но `renderer` будет нужен для прореживания ? Ему можно как-то подсунуть этот XYStepChart ?

**Comment by LeKaitoW** [comment]
Да, нужен.
Это может быть `renderer` на основе `SamplingXYLineRenderer`, который есть в JFreeChart. Надо только заставить его делать график ступенчатым и не искажать исходный - именно это и сделал Лёша в своём прореживателе.
Получается прореживатель, использующий часть из `SamplingXYLineRenderer` и часть из `XYStepRenderer`.

**Comment by aurusov** [comment]
Хорошо, тогда эту задачу можно закрывать и переходить к #6. Бранч пусть пока повисит. Для прореживателя надо тоже завести отдельную фичю.
