### ISSUE TITLE
 Сравнение и выбор библиотек построения графиков

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-chart#2]
Сравнить между собой библиотеки
- JFreeChart
- JGraphX
- JavaFX
- SWTChart

**Comment by LeKaitoW** [comment]
JGraphX - графическая библиотека без возможности построения графиков.
JavaFX - не работает с Java 8.
SWTChart - принимает только массивы double, нельзя передавать данные в реальном времени.
