### ISSUE TITLE
Оценка быстродействия JFreeChart

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-chart#3]
Сравнить быстродействие между SWT, AWT и Bridge на размерах от 1.000.000 до 10.000.000 с прореживанием и без.

**Comment by LeKaitoW** [comment]
Сравнение быстродействия:
![test1](https://cloud.githubusercontent.com/assets/10632455/6474323/357d7f70-c219-11e4-8c95-7208603c8907.JPG)
После теста на win7 совсем расхотелось использовать бридж - график не отображается, пока не будет щелчка мышкой по области построения. В некоторых случаях периодически пропадает до следующего щелчка.
С прореживанием разницы между AWT и SWT практически нет.

**Comment by aurusov** [comment]
Отчёт в секундах
