### ISSUE TITLE
Повторное использование XYStepChart

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-chart#7]
В текущей схеме мы подаём на вход XYStepChart dataset, который потом прореживаем, но приходится руками рисовать ступеньки. Получается, что XYStepChart не используется. Предлагаются проверить пару гипотез
- можно ли менять dataset для уже созданного графика
- можно ли повторно использовать отрисовку из XYStepChart в самодельном рендерере

**Comment by aurusov** [comment]
Предлагается
- написать свой

``` java
Sampler: public XYStepRenderer
```
- один раз передать его графику
- каждый раз возвращать новые данные графику (подойдет реализация #8: можно по пробелу менять/добавлять данные, можно по таймеру)
- перекрыть `drawItem`, прореживать `XYDataset dataset`, передавать уже прореженный `sample_dataset` в аналогичный метод предка

**Comment by LeKaitoW** [comment]
Метод `drawItem` рисует по одной точке, а вот `PlotXY` вызывает `drawItem` в цикле. Значит, перекрывать стоит этот `PlotXY`.

**Comment by aurusov** [comment]
Согласен
